### ISSUE TITLE
file format "file"

### ISSUE THREAD

**Issue by christianclapson** [thebetioplane/osuReplayEditorV3#1]
when I click "export as .osr" I check my replay folder and its a "file" rather than a "osr" 
![Screen Shot 2021-01-16 at 10 08 32 pm](https://user-images.githubusercontent.com/38335453/104810309-c7075180-5847-11eb-80c1-24fb4cec2f99.png)

**Comment by thebetioplane** [comment]
Thanks, this will be fixed with the next update I push. In the meantime you can get around this by adding ".osr" to the end of the file name in the export dialog.

I'll keep this issue open until it's fixed though.

**Comment by christianclapson** [comment]
after adding ".osr" at the end I get this error when trying to play the replay "this score has no replay data saved"

**Comment by thebetioplane** [comment]
That error is unrelated, but try clearing all local scores for a map. osu! will sometimes cache replays and never re-read the file.

**Comment by thebetioplane** [comment]
I've fixed the export dialog in the latest update, if you are still having the second problem then open another issue.
