### ISSUE TITLE
bug "md5 was incorrect length"

### ISSUE THREAD

**Issue by minoto2** [thebetioplane/osuReplayEditorV3#12]
i delete and redowload all the files and i have this problem "md5 was incorrect length"

**Comment by thebetioplane** [comment]
If it happens during startup it means osu!.db is bad. Try deleting it and run osu! to rebuild it.

If it happens while loading a replay then some other problem

**Comment by zxc7god** [comment]
It happens even after i recreated osu.db multiple times. Do you know what else can cause it?

**Comment by thebetioplane** [comment]
Closing 6 month old issue that appears dead... if this is a problem you still have feel free to open another.
