### ISSUE TITLE
Older client replay

### ISSUE THREAD

**Issue by KecHik445** [thebetioplane/osuReplayEditorV3#14]
Can you make it compatible with old replay? v2 can handle old replay but not v3. Hope you can fix it :D

**Comment by thebetioplane** [comment]
How old are we talking? I didn't know that replay format changed in the last 5 years.

The osu!.db format did, but osu!.db formats are all over the place so I don't really want to support anything but the latest.

**Comment by KecHik445** [comment]
Im trying to edit old Cookiezi/rrtyui plays the were like 30fps replay. But everytime I drag the reply to V3 its crash. But its working on V2.

**Comment by thebetioplane** [comment]
Can you upload one of those replays that crashes here?

**Comment by KecHik445** [comment]
here the the example [Cookiezi's Big Black](https://drive.google.com/file/d/11LgKjJxCu732srk9fn3ch5OIal8UVwII/view?usp=sharing).

**Comment by thebetioplane** [comment]
Fixed

**Comment by KecHik445** [comment]
THANK YOU!!
