### ISSUE TITLE
osu_db_path trouble issues

### ISSUE THREAD

**Issue by Zeus16** [thebetioplane/osuReplayEditorV3#15]
C:\osu!\osu!.db dont really know how to fix this pls help
![wasdw](https://user-images.githubusercontent.com/79646283/109162261-daea8100-772c-11eb-9431-8d5da1fec1e4.JPG)

**Comment by thebetioplane** [comment]
In the same directory as the .exe you have a file called config.txt

It needs to point to your osu! installation, the default is C:\osu! which is probably not correct for many users.

Please locate your osu!.db in the osu! installation folder (try right clicking osu shortcut -- Open file location), and then update config.txt accordingly.
