### ISSUE TITLE
error loading replay

### ISSUE THREAD

**Issue by AkuLABLYAT** [thebetioplane/osuReplayEditorV3#19]
![image](https://user-images.githubusercontent.com/84673957/119265846-f3195180-bbf0-11eb-9973-0f07c00edc16.png)
I configured everything in the config.txt file. In the replay editor, I selected the desired replay and clicked / open / after which I received an error ( screenshot attached ) (I use Google translate)

**Comment by Hazuki-san** [comment]
Do you linked your osu!.db yet? and set the songs folder in a proper place?

**Comment by AkuLABLYAT** [comment]
![image](https://user-images.githubusercontent.com/84673957/119265971-8b173b00-bbf1-11eb-958e-5ecfe4de120e.png)

**Comment by AkuLABLYAT** [comment]
> Do you linked your osu!.db yet? and set the songs folder in a proper place?

yes

**Comment by Hazuki-san** [comment]
Your osu!.db path is wrong, change it.

**Comment by Hazuki-san** [comment]
This is example:
```
# Settings file
# Blank lines and lines starting with '#' are ignored

# Path to osu db
# File must exist
# Required - Must have a value
osu_db_path = C:\Users\Aoba\AppData\Local\osu!\osu!.db

# Path to song folder
# Folder must exist
# Required - Must have a value
osu_song_folder = C:\Users\Aoba\AppData\Local\osu!\Songs\

# Path to replay folder, used by "quick load"
# Folder must exist
# Not Required - Can be left blank or deleted
osu_replay_folder = C:\Users\Aoba\AppData\Local\osu!\Replays\

# Url for automatic updates
# Not Required - Can be left blank or deleted
update_url = https://raw.githubusercontent.com/thebetioplane/osuReplayEditorV3/master/
```

**Comment by AkuLABLYAT** [comment]
thanks, I'll try now

**Comment by AkuLABLYAT** [comment]
works, thanks a lot !!!!

**Comment by Hazuki-san** [comment]
Please close the issue, thanks.
