### ISSUE TITLE
how to move cursor?

### ISSUE THREAD

**Issue by Zxya1** [thebetioplane/osuReplayEditorV3#20]
how do i move the cursor in the replay editor? does it just change taps?

**Comment by thebetioplane** [comment]
Something like this. You have to use "Mark In" and "Mark Out" to create a selection, then you can click and drag the middle mark (white triangle). A little clunky still, I have some ideas on how to improve cursor edits.

https://user-images.githubusercontent.com/13561330/123803685-07312c80-d8dc-11eb-9f13-15691c214b6f.mp4

**Comment by Zxya1** [comment]
> Something like this. You have to use "Mark In" and "Mark Out" to create a selection, then you can click and drag the middle mark (white triangle). A little clunky still, I have some ideas on how to improve cursor edits.
> 
>  cc1624972344.mp4

thanks dude
