### ISSUE TITLE
Crash on startup help

### ISSUE THREAD

**Issue by CillClick** [thebetioplane/osuReplayEditorV3#22]
### So i try to start i up and it just hits  me with **(crash log incoming)**

2021-07-13 21:18:19
System.DllNotFoundException: Unable to load DLL file ReplayEditor.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    at osuReplayEditor.API.Init (IntPtr hWnd, String osuDBPath, String songFolderPath)
    at osuReplayEditor.Canvas.Begin ()
    at osuReplayEditor.MainForm..ctor ()
    at osuReplayEditor.Program.Main2 ()
    at osuReplayEditor.Program.Main (String [] args)

The text is prob scuffed but i just ran it through google translate bc it was swedish
I tried redownloading it but same issue, and ive tried \, \\, //, / in the directory so idk what im doing wrong here

**Comment by Hazuki-san** [comment]
Well, the error is obvious, you're missing ReplayEditor.dll

**Comment by CillClick** [comment]
no i have replayeditor.dll, is it supposed to be in the same folder as osureplayeditor.exe or something?

**Comment by thebetioplane** [comment]
How did you download it, did you use the zip file from the releases page?

https://github.com/thebetioplane/osuReplayEditorV3/archive/beta.zip

That has the directory structure you want. Yes it is supposed to be in the same folder that you are running the exe out of.

> and ive tried , \, //, / in the directory so idk what im doing wrong here

Can you elaborate what you mean by this? Where are these slashes going?

**Comment by Hazuki-san** [comment]
Show your directory, like this.
![image](https://user-images.githubusercontent.com/27200811/125663299-f43fc6a5-ae42-4058-9e21-7bf8c76938a3.png)

**Comment by CillClick** [comment]
holy fuck im late sorry, heres my directory 
![bandicam 2021-07-14 19-27-24-446](https://user-images.githubusercontent.com/84600373/125665959-b44b510c-2fdc-4414-86fe-0ba942613648.png)

**Comment by CillClick** [comment]
oh is it the ore.db3 thing or something? becuase i didnt get that when i downloaded it

**Comment by Hazuki-san** [comment]
Those db3 are generated by the program itself, make sure you unblock all files.

by right clicking the file, click Properties and press Unblock.

**Comment by CillClick** [comment]
can you elaborate?
which file and what unblock, becuase it isnt showing up

**Comment by thebetioplane** [comment]
Are you running 64 bit or 32 bit Windows? Do you have a Microsoft Visual C++ Redistributable installed for x64 for 2010 or later (see screenshot)?

![screenshot](https://user-images.githubusercontent.com/13561330/125695094-3aac9af3-9c81-45ba-98fe-be1917435e16.png)

**Comment by thebetioplane** [comment]
Just elaborating here, the error is slightly misleading. It is true that a DLL is missing, but it could any dependency of ReplayEditor.dll. 

Here is a list:
```
ReplayEditor.dll
bass.dll
bass_fx.dll

kernel32.dll
user32.dll
gdi32.dll
winspool.dll
comdlg32.dll
advapi32.dll
shell32.dll
ole32.dll
oleaut32.dll
uuid.dll
odbc32.dll
odbccp32.dll
Opengl32.dll
```

The first three I package but the rest come from a Visual C++ framework and potentially your graphics driver for Opengl32.dll.

> Hazuki-san commented 4 hours ago
> make sure you unblock all files.
> by right clicking the file, click Properties and press Unblock.

I don't know what "Unblocking" means, but if you are talking about an anti virus issue perhaps it could be that too. You should add exceptions to all the .exe's and .dll's.

**Comment by Hazuki-san** [comment]
> I don't know what "Unblocking" means, but if you are talking about an anti virus issue perhaps it could be that too. You should add exceptions to all the .exe's and .dll's.

Oh, I mean some Windows has the blocked files from internet thing when downloaded, but I think that's not the case now after I look for the error code. The dependencies are missing.

**Comment by CillClick** [comment]
nope. downloaded everything, still nothing.
same crash log.

**Comment by thebetioplane** [comment]
I haven't been able to think of any other ideas btw, but if you find out what the problem is be sure to put it here.

**Comment by Hazuki-san** [comment]
> nope. downloaded everything, still nothing.
> same crash log.

You can use the dumpbin tool to find out the required DLL dependencies:

**Comment by thebetioplane** [comment]
The only thing is before I said it needed to be 2010 or higher but it needs to be the 2015-2019, if that's not the version you see in control panel then you will this.

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Download both:

x86: [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe)
x64: [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by CillClick** [comment]
**o shit im late**
holy shit it atually worked

**Comment by CillClick** [comment]
well thanks
