### ISSUE TITLE
cursor lags while editing

### ISSUE THREAD

**Issue by Shinober** [thebetioplane/osuReplayEditorV3#26]
https://user-images.githubusercontent.com/62177182/131077386-c37c4ebb-33f5-44de-aa7f-da806e0debd3.mp4

**Comment by thebetioplane** [comment]
I think I fixed it... not easy to test since I get it inconsistently. Are you still experiencing it?

**Comment by Shinober** [comment]
> I think I fixed it... not easy to test since I get it inconsistently. Are you still experiencing it?

im tested it, so yea, you fixed it. nice ty
