### ISSUE TITLE
The error "replay contains no cursor data"

### ISSUE THREAD

**Issue by demchenko-art** [thebetioplane/osuReplayEditorV3#28]
The error "replay contains no cursor data". When adding a replay to the program, this error pops up. What to do?

**Comment by Hazuki-san** [comment]
Can you provide the replay file?

**Comment by thebetioplane** [comment]
Some replays only contain the score info (metadata). For example, if you download your top play off the scoreboard and it's not in the top 50 and osu didn't cache it, then it contains no cursor data.

When you open this replay in osu, does the button "Watch Replay" appear?

**Comment by demchenko-art** [comment]
> Some replays only contain the score info (metadata). For example, if you download your top play off the scoreboard and it's not in the top 100 and osu didn't cache it, then it contains no cursor data.
> 
> When you open this replay in osu, does the button "Watch Replay" appear?

Yes, the button appears. I apologize to everyone for not answering for a long time.

**Comment by thebetioplane** [comment]
If osu! shows it as having cursor data and the replay editor is saying that there is none then it could be a bug.

Could you upload the replay so I can examine what's different about this file?

**Comment by thebetioplane** [comment]
osu! is reporting it as not having cursor data when you try to watch it:
![image](https://user-images.githubusercontent.com/13561330/136993412-f4f3dc27-2e3a-455e-a7d3-93f66f97190e.png)

A hex view also shows there is no cursor data here (complete file size = 129 bytes -- very small):
![image](https://user-images.githubusercontent.com/13561330/136993524-41a1bd9d-df82-4c96-844d-482369ce6385.png)

Unless this file was the result of the replay editor cutting off your cursor data then this isn't really a bug. The replay simple has no data to edit.

**Comment by thebetioplane** [comment]
Closing this old issue that I believe to be resolved. If it's not then you can just open it back up.

**Comment by LordKamaYT** [comment]
Hi! I'm having the same problem and it seems to come from the editor
