### ISSUE TITLE
Editor doesnt display some sliderbreaks as misses

### ISSUE THREAD

**Issue by whatisauser** [thebetioplane/osuReplayEditorV3#33]
for example, vanity clock, sliderbreaks on the sliderstream arent counted as misses, some slow sliders on flamewall, and a lot of other maps

**Comment by thebetioplane** [comment]
Nothing but the initial hit is supported with sliders. Will fix eventually.....

**Comment by thebetioplane** [comment]
Most recent update added slider ticks and therefore some slider scoring
