### ISSUE TITLE
Long multi-point slider breaks

### ISSUE THREAD

**Issue by AwesomeGamer89** [thebetioplane/osuReplayEditorV3#36]
https://user-images.githubusercontent.com/22873716/150053454-5235aa42-0584-4acb-ad6e-6ac8b99f7372.mp4

Map: https://osu.ppy.sh/beatmapsets/1127009#osu/2354761

Song Time (ms): 519627

**Comment by thebetioplane** [comment]
Thank you for identifying this, the most recent update should have fixed it.
