### ISSUE TITLE
Slow sliders going too fast

### ISSUE THREAD

**Issue by AwesomeGamer89** [thebetioplane/osuReplayEditorV3#37]
Map: https://osu.ppy.sh/beatmapsets/1127009#osu/2354761

Song Time (ms): 221592 (Also at 111760)

https://user-images.githubusercontent.com/22873716/150425255-f0a59480-37e0-4204-9902-9be5cef98bfd.mp4

)

**Comment by thebetioplane** [comment]
Fixed, was an issue when timing points are stacked on top of each other.
