### ISSUE TITLE
Slider ticks are not showing up where they are supposed to on fast sliders

### ISSUE THREAD

**Issue by AwesomeGamer89** [thebetioplane/osuReplayEditorV3#38]
![Untitled](https://user-images.githubusercontent.com/22873716/150441116-4bce90b8-b266-4947-913e-f037b3398afc.png)

Map: https://osu.ppy.sh/beatmapsets/365053#osu/801303

Song Time (ms): 94676

**Comment by thebetioplane** [comment]
Fixed just now
