### ISSUE TITLE
MD5 was incorrect length

### ISSUE THREAD

**Issue by xxCherry** [thebetioplane/osuReplayEditorV3#4]
The moment i open executable, it crashes with no error, only windows report thing process is created.
Does it need something to be installed?

**Comment by xxCherry** [comment]
[osuReplayEditor.exe.12136.dmp.zip](https://github.com/thebetioplane/osuReplayEditorV3/files/5838136/osuReplayEditor.exe.12136.dmp.zip)

Dump if needed

**Comment by xxCherry** [comment]
ah, sorry, i forgot to disable something.

**Comment by xxCherry** [comment]
![изображение](https://user-images.githubusercontent.com/42537021/105083670-4abe7980-5aa6-11eb-8328-194b1fc76b19.png)
Now this problem.

**Comment by thebetioplane** [comment]
If this happens at startup, then it is a problem reading the osu!.db. You can try deleting it and having osu! rebuild it.

Error message a bit poor, osu!.db gives me a quite the headache because I have found that sometimes old versions of it will still have fields found only in newer versions.

**Comment by xxCherry** [comment]
still

**Comment by xxCherry** [comment]
nvm, works now, thanks
