### ISSUE TITLE
no scorev2 support

### ISSUE THREAD

**Issue by cptslow-osu** [thebetioplane/osuReplayEditorV3#43]
title, metadata section does not support sv2

**Comment by Kuuuube** [comment]
Just gonna put this here for reference on which mods are what: https://github.com/Kuuuube/rxhddt/blob/master/rxhddt/Util/OsuHelper.cs#L216-L247. Seems like adding it would be a very simple change to make.

Would be cool to see ScoreV2, Mirror and TargetPractice all added. Though TargetPractice isn't as simple as slapping the mod onto the replay so maybe not that.

**Comment by thebetioplane** [comment]
I just added all the mods to the metadata editor and rearranged them to be laid out in a (somewhat) more organized pattern.
