### ISSUE TITLE
Points randomly dissapear making the osr unreadable after export.

### ISSUE THREAD

**Issue by AG89** [thebetioplane/osuReplayEditorV3#46]
This issue happens randomly when selecting and dragging between multiple points
osr (contains missing points):
[Issue.zip](https://github.com/thebetioplane/osuReplayEditorV3/files/8191524/Issue.zip)
Beatmap: https://osu.ppy.sh/beatmapsets/1487999#osu/3050529
Time: 01:41:202
Video:

https://user-images.githubusercontent.com/22873716/156900951-6a325cd2-fbce-4fd2-922e-4a1f46af5ef0.mp4

**Comment by thebetioplane** [comment]
This has been fixed this week, I think. Reopen if you are still encountering this.
