### ISSUE TITLE
Feature Request: Add Scorev2 as a mod

### ISSUE THREAD

**Issue by statl0rd** [thebetioplane/osuReplayEditorV3#49]
Please?

**Comment by thebetioplane** [comment]
![image](https://user-images.githubusercontent.com/13561330/164753276-0457bdcd-36ae-487c-8fb8-db93f6b242ad.png)

Is it bugged for you?

**Comment by thebetioplane** [comment]
Closing this old issue, if is anything to add then you can reopen it
