### ISSUE TITLE
Replay points randomly get moved to NaN

### ISSUE THREAD

**Issue by AG89** [thebetioplane/osuReplayEditorV3#50]
replay:
[khag.zip](https://github.com/thebetioplane/osuReplayEditorV3/files/8546127/khag.zip)
map: https://osu.ppy.sh/beatmapsets/1602507#osu/3272642

I don't really know what causes this, but I think it has something to do with undoing point movements. There's no specific time I can give, since I can't see the point or the time that it happens at.

**Comment by thebetioplane** [comment]
This is what was causing osu! to treat some beatmaps as "No cursor data" I'm pretty sure. While I patched it to not produce export the NaN values this root cause is not fixed yet.

**Comment by thebetioplane** [comment]
This has been fixed.
