### ISSUE TITLE
Error while parsing config

### ISSUE THREAD

**Issue by A17Forkybest303** [thebetioplane/osuReplayEditorV3#51]
![image](https://user-images.githubusercontent.com/78596321/166616746-7c2fefb4-8fd7-4715-b7bf-ce118c174994.png)
This error message displays despite having osu!.db being in the correct location specified
![image](https://user-images.githubusercontent.com/78596321/166616820-153bcd1d-675a-43bd-a21b-91fd3bb1a4f8.png)

**Comment by thebetioplane** [comment]
Can you show a screenshot or something with the path of your osu! installation? Most people do not have it in C:\osu! by default so you need to edit the file

**Comment by A17Forkybest303** [comment]
C:\Users\<Username>\AppData\Local\osu!\"osu!.db"
![image](https://user-images.githubusercontent.com/78596321/166919685-f11b0ddb-429b-41a2-84ac-ae4f88dda425.png)

**Comment by thebetioplane** [comment]
The path that you just wrote needs to be written into config.txt
config.txt is meant to be modified to describe your installation

**Comment by thebetioplane** [comment]
Closing this as I believe it is resolved. If it isn't resolved you can reopen it.
