### ISSUE TITLE
I still get this error

### ISSUE THREAD

**Issue by 2coolCandy** [thebetioplane/osuReplayEditorV3#52]
![Screenshot 2022-05-15 004007](https://user-images.githubusercontent.com/105549031/168426160-ac974961-3a8c-4a12-8142-01ec3832d4b8.png)
i put my osu instalation folder but still dosen t work

**Comment by thebetioplane** [comment]
You need a path not to the installation folder but a path to the osu!.db

So in this case it would be C:\Users\.......\Local\osu!\osu!.db

**Comment by 2coolCandy** [comment]
> You need a path not to the installation folder but a path to the osu!.db
> 
> So in this case it would be C:\Users.......\Local\osu!\osu!.db

thx but i have a problem if i try to use it on a replay cheat is not going well why?

**Comment by thebetioplane** [comment]
Closing this as I believe it is resolved. If it isn't resolved you can reopen it.
