### ISSUE TITLE
d.b. folder doesn't get recognized

### ISSUE THREAD

**Issue by dancemoves** [thebetioplane/osuReplayEditorV3#55]
I created the d.b. folder in C:\osu!\osu!\.db but the editor just doesn't open for unfortunately, so I wanna know if someone here has found a way to fix that issue incase you had it.

**Comment by thebetioplane** [comment]
You mentioned that you "created" the db folder. You are not supposed to create the folder but instead edit the `config.txt` to point it to the existing osu! installation.

**Comment by dancemoves** [comment]
> 

do I have to redownload it now? I don't really get what I have to do now, it would be cool if u could explain. Also thanks for the quick reply :D

**Comment by thebetioplane** [comment]
First find your osu! folder. If you right click your osu! icon and hit "Open Folder Location you can find it. Put that path into the config.txt

Example: if you right click and it opens up `C:\Users\username\AppData\Local\osu!` then you would put in config.txt `C:\Users\username\AppData\Local\osu!\osu!.db`

**Comment by thebetioplane** [comment]
Closing this, download the latest update and delete the config.txt file there is now a dialog to choose the osu!.db. If you are still having problems feel free to reopen this issue.
