### ISSUE TITLE
"curve size too small" error

### ISSUE THREAD

**Issue by Tulip-0333** [thebetioplane/osuReplayEditorV3#57]
I'm trying to open a replay (
[This](https://github.com/thebetioplane/osuReplayEditorV3/files/9591983/Change.the.file.extension.to.osr.zip) ) and it comes up with an error "curve size too small"
![image](https://user-images.githubusercontent.com/93089383/190863720-8cdc3b16-7f3f-40d7-b0ed-41d0b57b148a.png)
and I want some help.

**Comment by thebetioplane** [comment]
Sorry I don't have that beatmap installed, which beatmap is it?

**Comment by Tulip-0333** [comment]
Sorry for a bit late response, it's `https://osu.ppy.sh/beatmapsets/710630` [this].

**Comment by thebetioplane** [comment]
Sorry I neglected osu replay editor. If you are still there, I did download that beatmap but your replay still didn't match anything I have downloaded. Also I opened the editor on some of the high scores for that map and I didn't get the error with them. I think either the beatmap you provided is incorrect, or the beatmap was updated over the last year or whatever and no longer has the issue?

**Comment by Tulip-0333** [comment]
Honestly just gonna say I got banned on osu and barely play anymore
Sorry for kinda wasting your time, good day.
