### ISSUE TITLE
Error while parsing config

### ISSUE THREAD

**Issue by tzm13** [thebetioplane/osuReplayEditorV3#61]
I'm getting the following error when trying to run Replay Editor. I literally copy-pasted the address of the osu!.db file so I'm not too sure what I'm doing wrong. Any suggestions on how to fix this?

![image_2023-04-02_185021170](https://user-images.githubusercontent.com/129682407/229367104-dbd0dfba-c2d9-4b22-90d9-10409c72592f.png)

**Comment by thebetioplane** [comment]
There are only two scenarios here:

1. The file does not exist.
2. You do not have sufficient permissions to read the file.

If you are certain the file exists, perhaps you can try running the program as an administrator to confirm that it's a permission issue, and then figure out why you don't have ownership.

**Comment by thebetioplane** [comment]
Closing this, download the latest update and delete the config.txt file there is now a dialog to choose the osu!.db. If you are still having problems feel free to reopen this issue.
