### ISSUE TITLE
Point pos gets randomly reset when selecting, uisng marker/anchor buttons, using key presses buttons

### ISSUE THREAD

**Issue by AG89** [thebetioplane/osuReplayEditorV3#65]
Point pos gets randomly reset when selecting, uisng marker/anchor buttons, using key presses buttons.
works on any map and any replay

https://github.com/thebetioplane/osuReplayEditorV3/assets/22873716/2c41d9a6-d9ea-421d-9bac-b14e0a666820

**Comment by thebetioplane** [comment]
Thanks for reporting this, this was a big bug. Fixed.
