### ISSUE TITLE
Yayyy it crashed again

### ISSUE THREAD

**Issue by LordKamaYT** [thebetioplane/osuReplayEditorV3#67]
UTC: 2023-11-25 15:52:04
System.DllNotFoundException: Impossible de charger la DLL 'ReplayEditor.dll': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
   à osuReplayEditor.API.Init(IntPtr hWnd, String osuDBPath, String songFolderPath)
   à osuReplayEditor.Canvas.Begin()
   à osuReplayEditor.MainForm..ctor()
   à osuReplayEditor.Program.Main2()
   à osuReplayEditor.Program.Main(String[] args)

**Comment by thebetioplane** [comment]
Try installing Microsoft Visual C++ Redistributable 2015-2022.

Download link: https://aka.ms/vs/17/release/vc_redist.x64.exe

Installation instructions: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by LordKamaYT** [comment]
Damn this isnt my main pc and i dont have admin rip. Maybe an online version soon ? ^^

**Comment by thebetioplane** [comment]
Just FYI one year two months later and you don't need Microsoft Visual C++ Redistributable anymore since it is now statically linked. Was probably a mistake on my part not having it like this from the start. No more DllNotFoundException
