### ISSUE TITLE
Undo/Redo features

### ISSUE THREAD

**Issue by Hazuki-san** [thebetioplane/osuReplayEditorV3#7]
When I was editing the replay, somehow the cursor disappeared and made the replay corrupted. Or maybe sometime the cursor went to the place that very very far from playfield.

So the Undo/Redo feature might be useful in this.

**Comment by thebetioplane** [comment]
Yes I have had that problem before myself. While I don't yet know the root cause I'll add undo and redo soon.

**Comment by thebetioplane** [comment]
Undo is added, redo is not. I'll add redo soon.

**Comment by thebetioplane** [comment]
Took my time on that one but redo is now here.
Edit->Undo OR Ctrl+Z
Edit->Redo OR Ctrl+Y

**Comment by Hazuki-san** [comment]
thanks!
